const PARK_EDEN = {
  id: "eden",
  name: "Birds of Eden",
  subtitle: "World's Largest Free-Flight Aviary",
  icon: "🦜",
  species: [
    // ══ TURACOS ══
    { id: "knysna-turaco", r: "Common", t: "Flagship species of the aviary. Listen for their 'kok-kok-kok' call in the canopy. Crimson wings flash in flight." },
    { id: "purple-crested-turaco", r: "Common", t: "Spectacular purple crest catches the light. Look in the upper canopy near fruiting trees." },
    { id: "livingstones-turaco", r: "Uncommon", t: "Green plumage with white-tipped crest. Blends into the canopy — listen for its call to locate it." },
    { id: "red-crested-turaco", r: "Uncommon", t: "Exotic species with a vivid red crest. Often perches on exposed branches near the walkway." },
    { id: "rosss-turaco", r: "Rare", t: "Deep violet-blue plumage and yellow bill are unmistakable. One of the aviary's most photogenic residents." },
    { id: "grey-go-away-bird", r: "Common", t: "Loud 'go-away' call echoes through the dome. Often seen on prominent perches near the entrance." },
    // ══ PARROTS & LOVEBIRDS ══
    { id: "blue-and-yellow-macaw", r: "Common", t: "Hard to miss! Often perched high in the dome or flying across the canopy with loud squawking calls." },
    { id: "scarlet-macaw", r: "Uncommon", t: "Brilliant red plumage stands out against the green canopy. Usually seen in pairs near the top of the dome." },
    { id: "african-grey-parrot", r: "Uncommon", t: "Look for their grey plumage and red tail. Often near feeding stations. Listen for their remarkable mimicry." },
    { id: "ring-necked-parakeet", r: "Common", t: "Fast-flying bright green parakeets. Males have the distinctive neck ring. Often in small, noisy flocks." },
    { id: "sun-conure", r: "Uncommon", t: "Brilliant yellow and orange plumage makes them easy to spot. Usually seen near feeding platforms." },
    { id: "cockatiel", r: "Common", t: "Look for the distinctive yellow crest and orange cheek patches. Often perched near the rest area." },
    { id: "budgerigar", r: "Common", t: "Small bright green parakeets, often in chattering groups near seed feeders." },
    { id: "peach-faced-lovebird", r: "Common", t: "Pairs sit close together preening. Look for their rosy-pink faces near nesting boxes along the walkway." },
    { id: "fischers-lovebird", r: "Uncommon", t: "Orange face and white eye-ring distinguish them from peach-faced lovebirds. Check the feeding stations." },
    { id: "black-cheeked-lovebird", r: "Rare", t: "Vulnerable species — a conservation highlight. Dark cheeks and red bill. Check mixed lovebird groups carefully." },
    { id: "yellow-collared-lovebird", r: "Uncommon", t: "Dark head with yellow collar is distinctive. Often in noisy groups near the lovebird nesting area." },
    { id: "cape-parrot", r: "Rare", t: "South Africa's only endemic parrot. A conservation priority species. Look for orange shoulder patches on green plumage." },
    { id: "brown-headed-parrot", r: "Uncommon", t: "Quiet compared to other parrots. Brown head and green body. Yellow underwing visible in flight." },
    { id: "meyers-parrot", r: "Uncommon", t: "Brown body with teal and yellow patches. Usually in pairs, quieter than most parrots in the aviary." },
    // ══ PHEASANTS & PEAFOWL ══
    { id: "indian-peafowl", r: "Common", t: "Males display their spectacular tail fans on the forest floor. Best photographed near the entrance clearing." },
    { id: "golden-pheasant", r: "Uncommon", t: "Males are breathtakingly colourful. Forages on the forest floor — scan the undergrowth near the lower walkway." },
    { id: "lady-amhersts-pheasant", r: "Rare", t: "Extraordinarily long white tail visible in the undergrowth. Males display their black-and-white cape in the shaded areas." },
    { id: "silver-pheasant", r: "Uncommon", t: "Males are silver-white with black underparts. Easier to spot in the more open sections of the aviary floor." },
    { id: "helmeted-guineafowl", r: "Common", t: "Noisy flocks forage on the forest floor throughout the aviary. Their alarm calls alert you to other activity." },
    // ══ DOVES & PIGEONS ══
    { id: "african-green-pigeon", r: "Common", t: "Surprisingly hard to spot despite vivid green. Look for them feeding on fruit in the mid-canopy fig trees." },
    { id: "lemon-dove", r: "Uncommon", t: "A shy forest-floor species. Walk slowly and scan the ground in the darker sections of the aviary." },
    { id: "red-eyed-dove", r: "Common", t: "Listen for the mournful cooing throughout the dome. Red eye-ring visible at close range." },
    { id: "cape-turtle-dove", r: "Common", t: "Gentle 'work harder' call heard all day. Common along the walkway edges and near clearings." },
    { id: "tambourine-dove", r: "Uncommon", t: "Listen for its deep drumming call in the undergrowth. White face and breast contrast with brown back." },
    { id: "laughing-dove", r: "Common", t: "Small and delicate with a soft bubbling call. Often seen on the ground near the entrance and exit areas." },
    // ══ HORNBILLS ══
    { id: "trumpeter-hornbill", r: "Common", t: "Large and loud — their wailing call is unmistakable. Often seen flying between the tallest trees in the dome." },
    { id: "crowned-hornbill", r: "Common", t: "Red bill and casque are distinctive. Frequents the fruiting trees in the mid-level canopy." },
    // ══ KINGFISHERS ══
    { id: "half-collared-kingfisher", r: "Rare", t: "A stunning cobalt-blue gem. Search near the stream and pool areas — perches on low overhanging branches." },
    { id: "brown-hooded-kingfisher", r: "Common", t: "A woodland kingfisher that hunts insects, not fish. Red bill and brown hood. Listen for its descending whistle." },
    { id: "pied-kingfisher", r: "Uncommon", t: "Black and white hovering specialist. Check the stream and pool areas where it hovers before diving." },
    { id: "giant-kingfisher", r: "Rare", t: "Africa's largest kingfisher — impressive spotted plumage. Perches near the stream on overhanging branches." },
    // ══ BARBETS ══
    { id: "black-collared-barbet", r: "Common", t: "Red face and synchronised duetting make them easy to find. Common near fruiting trees throughout the aviary." },
    { id: "yellow-rumped-tinkerbird", r: "Common", t: "Persistent 'tink-tink-tink' call is one of the aviary's constant sounds. Small — look carefully in the canopy." },
    { id: "acacia-pied-barbet", r: "Uncommon", t: "Black and white with red forehead. Check dead branches where they drum and call. Less common than tinkerbirds." },
    { id: "red-fronted-tinkerbird", r: "Uncommon", t: "Similar tinkling call but look for the red forehead patch. Often in the lower canopy near the walkway." },
    { id: "crested-barbet", r: "Common", t: "Shaggy crest and colourful face make it unmistakable. Trilling call is constant. Feeds on the forest floor and low branches." },
    { id: "white-eared-barbet", r: "Uncommon", t: "Bold white ear patches on dark plumage. Found in the taller trees, especially near figs. Listen for its trilling call." },
    // ══ CUCKOOS ══
    { id: "klaass-cuckoo", r: "Rare", t: "Small and green — extremely difficult to spot. Listen for the plaintive 'meitjie' call from the upper canopy." },
    { id: "red-chested-cuckoo", r: "Uncommon", t: "The famous 'Piet-my-vrou' call identifies this summer visitor. Rarely seen despite the loud call." },
    { id: "burchells-coucal", r: "Uncommon", t: "Large cuckoo with a bubbling 'water bottle' call. Skulks in dense undergrowth near the stream area." },
    { id: "emerald-cuckoo", r: "Rare", t: "Brilliant green male is one of the aviary's hidden treasures. Listen for its melodious whistle in the high canopy." },
    // ══ MOUSEBIRDS ══
    { id: "speckled-mousebird", r: "Common", t: "Groups creep through bushes mouse-like with long tails trailing. Often seen sunbathing with wings spread." },
    { id: "red-faced-mousebird", r: "Uncommon", t: "Red face patch distinguishes from speckled. Look for huddles of birds on open branches in the morning sun." },
    { id: "white-backed-mousebird", r: "Uncommon", t: "Palest of the mousebirds with white back stripe visible in flight. Check fruiting shrubs along the walkway." },
    // ══ SUNBIRDS ══
    { id: "malachite-sunbird", r: "Uncommon", t: "Males are dazzling metallic green. Look for them hovering at flowering plants along the sunlit edges of the dome." },
    { id: "southern-double-collared-sunbird", r: "Common", t: "Tiny jewel with a narrow red breast band. Visits flowering plants throughout the aviary." },
    { id: "greater-double-collared-sunbird", r: "Common", t: "Larger than its southern cousin with a wider red band. Compare the two species at the same flowering bushes." },
    { id: "amethyst-sunbird", r: "Uncommon", t: "Males look black until the light catches the purple throat. Best seen in direct sunlight near flowering aloes." },
    { id: "collared-sunbird", r: "Common", t: "Tiny and short-billed with green head and yellow belly. Flits rapidly between flowers in the lower vegetation." },
    { id: "olive-sunbird", r: "Common", t: "The plain olive one — identified by lack of iridescence. Very common but easily overlooked among the showier species." },
    // ══ WEAVERS & BISHOPS ══
    { id: "southern-masked-weaver", r: "Common", t: "Males weave nests from grass strips near the entrance. Watching nest construction is fascinating." },
    { id: "spectacled-weaver", r: "Uncommon", t: "Black eye-line gives a spectacled look. Builds a nest with a long entrance tunnel. Pairs forage together." },
    { id: "village-weaver", r: "Common", t: "Large untidy nests in colonies. Males display hanging upside-down from nests while fluttering wings." },
    { id: "thick-billed-weaver", r: "Uncommon", t: "Heavy bill is diagnostic. Less colourful than other weavers. Check reed beds and dense vegetation." },
    { id: "cape-weaver", r: "Common", t: "Bright yellow male with orange wash on face. Look for hanging nests near the stream section." },
    { id: "yellow-bishop", r: "Uncommon", t: "Breeding males puff up yellow plumage in spectacular display. Look in grassier areas near the aviary edges." },
    { id: "southern-red-bishop", r: "Common", t: "Breeding males glow red and black — impossible to miss. Display flights over reedy areas near the water." },
    // ══ FINCHES & WAXBILLS ══
    { id: "swee-waxbill", r: "Uncommon", t: "Tiny grey bird with red rump and face. Forages on grass seeds near the ground along quiet sections of the walkway." },
    { id: "common-waxbill", r: "Common", t: "Small brown finch with red bill and eye stripe. Look for flocks feeding in grass along the edges of the path." },
    { id: "african-firefinch", r: "Uncommon", t: "Males are bright crimson red. Feeds on the forest floor near dense bushes. Often near lovebird and waxbill flocks." },
    { id: "cape-canary", r: "Common", t: "Cheerful canary song brightens the aviary. Yellow-green plumage — look for them on exposed perches singing." },
    { id: "forest-canary", r: "Uncommon", t: "Streakier and duller than Cape canary. Sings from the canopy in the denser forest sections." },
    { id: "java-sparrow", r: "Uncommon", t: "Bold black head, white cheeks, and pink bill. Check feeding stations where they congregate in small groups." },
    { id: "red-billed-firefinch", r: "Common", t: "Tiny red finch — males are deeply crimson. Common near seed feeders and on the ground under fruiting bushes." },
    { id: "blue-waxbill", r: "Common", t: "Delicate powder-blue face and breast. Look for small flocks on the ground near water features." },
    { id: "violet-eared-waxbill", r: "Rare", t: "Exquisite violet ear-patches reward careful observation. Shy — check among mixed waxbill flocks on the ground." },
    { id: "pin-tailed-whydah", r: "Uncommon", t: "Breeding males trail spectacular long tail feathers. Look for the bouncing display flight over open areas." },
    // ══ STARLINGS ══
    { id: "cape-starling", r: "Common", t: "Glossy blue-green plumage and orange eyes. Bold and approachable — often seen near picnic areas." },
    { id: "red-winged-starling", r: "Common", t: "Chestnut wing feathers flash in flight. Common around the entrance building and on prominent perches." },
    { id: "pied-starling", r: "Uncommon", t: "Dark brown with white belly. Endemic to southern Africa. Forages in small groups on the ground." },
    { id: "black-bellied-starling", r: "Uncommon", t: "Iridescent plumage shimmers purple-green. Feeds on fruit in the canopy — scan fruiting trees carefully." },
    { id: "wattled-starling", r: "Rare", t: "Breeding males have remarkable black wattles on bare yellow heads. Non-breeding birds are plain grey." },
    // ══ BULBULS ══
    { id: "dark-capped-bulbul", r: "Common", t: "One of the first birds you will hear — cheerful liquid call throughout the aviary. Yellow vent is diagnostic." },
    { id: "sombre-greenbul", r: "Common", t: "Plain olive-green. More often heard than seen — listen for its loud 'Willie' call in the dense canopy." },
    { id: "terrestrial-brownbul", r: "Uncommon", t: "Skulks on the forest floor turning over leaves. Walk slowly and scan the leaf litter in darker sections." },
    // ══ ROBIN-CHATS ══
    { id: "cape-robin-chat", r: "Common", t: "Rich song at dawn and dusk. Orange breast and white eyebrow. Confiding and easily approached along the walkway." },
    { id: "chorister-robin-chat", r: "Uncommon", t: "One of the aviary's finest singers. Listen for its extraordinary varied song from dense undergrowth at dawn." },
    { id: "red-capped-robin-chat", r: "Rare", t: "Vivid orange cap and blue-black back. Skulks in the densest undergrowth — its mimicry may help locate it." },
    { id: "brown-scrub-robin", r: "Uncommon", t: "Plain brown with rufous tail. Forages in deep shade among leaf litter. Frequently fans and raises its tail." },
    // ══ WARBLERS & FLYCATCHERS ══
    { id: "yellow-throated-woodland-warbler", r: "Uncommon", t: "Yellow throat and breast brighten the mid-canopy. Often hangs upside-down while gleaning insects from leaves." },
    { id: "bar-throated-apalis", r: "Uncommon", t: "Dark bar across the breast is diagnostic. Pairs forage actively — listen for their contact calls." },
    { id: "yellow-breasted-apalis", r: "Common", t: "Green above with bright yellow breast and a small dark spot. Very active and vocal in the undergrowth." },
    { id: "green-backed-camaroptera", r: "Common", t: "Bleating call is very common in the aviary. Small and restless — look for green back and grey underparts." },
    { id: "cape-batis", r: "Uncommon", t: "Small black and white flycatcher with chestnut breast band. Joins mixed bird parties moving through the canopy." },
    { id: "fiscal-flycatcher", r: "Uncommon", t: "Black and white — resembles a small shrike. Makes short sallies from prominent perches to catch insects." },
    { id: "african-dusky-flycatcher", r: "Common", t: "Plain grey-brown but energetic. Watch for aerial sallies from favourite perches along the walkway." },
    { id: "african-paradise-flycatcher", r: "Uncommon", t: "Long tail streamers and rufous plumage are stunning. Summer visitor — active in the canopy catching flying insects." },
    // ══ SHRIKES & BUSH-SHRIKES ══
    { id: "olive-bush-shrike", r: "Rare", t: "Secretive skulker in the dense canopy. Listen for its distinctive whistle to locate this elusive species." },
    { id: "southern-fiscal", r: "Common", t: "Bold black and white 'butcher bird'. Often perches prominently on railings and exposed branches near the path." },
    { id: "southern-tchagra", r: "Uncommon", t: "Forages near the ground in dense bush. Listen for its descending whistled call followed by a rattle." },
    { id: "black-backed-puffback", r: "Uncommon", t: "Males puff up white rump feathers into a conspicuous ball during display. Look for pairs in the mid-canopy." },
    { id: "southern-boubou", r: "Common", t: "Heard far more often than seen — pairs duet so precisely it sounds like one bird. Skulks in dense undergrowth." },
    { id: "bokmakierie", r: "Common", t: "Bright green and yellow with black necklace. Pairs call 'bok-makierie' together from prominent perches." },
    // ══ WOODPECKERS ══
    { id: "olive-woodpecker", r: "Uncommon", t: "Green plumage and red crown (males). Creeps along trunks in the denser forest sections of the aviary." },
    { id: "cardinal-woodpecker", r: "Common", t: "Africa's smallest woodpecker. Often in pairs working up tree trunks. Look for the small red nape patch." },
    { id: "knysna-woodpecker", r: "Rare", t: "A South African endemic — special sighting. Green with heavy spotting. Check larger tree trunks in the forest section." },
    // ══ PASSERINES & OTHER ══
    { id: "fork-tailed-drongo", r: "Common", t: "Glossy black with a forked tail. Expert mimic — listen for its imitations of other birds in the aviary." },
    { id: "black-headed-oriole", r: "Common", t: "Golden yellow with black head and coral-red bill. Beautiful liquid whistle. Look in the upper canopy." },
    { id: "green-wood-hoopoe", r: "Uncommon", t: "Cackling family groups probe bark with long curved red bills. Rocking display is entertaining to watch." },
    { id: "african-hoopoe", r: "Uncommon", t: "Cinnamon plumage with black-and-white wings and erectile crest. Probes the ground for grubs near clearings." },
    { id: "cape-wagtail", r: "Common", t: "Constantly wags its tail. Very confiding — often walks along the pathway right in front of visitors." },
    { id: "cape-sugarbird", r: "Rare", t: "Long-tailed males are spectacular. Associated with proteas — check flowering plants near the dome edges." },
    { id: "pied-crow", r: "Uncommon", t: "Large and intelligent. White breast patch is distinctive. Often seen soaring above the dome or perched on structures." },
    // ══ SWALLOWS ══
    { id: "white-throated-swallow", r: "Uncommon", t: "Glossy blue-black above with white throat. Swoops through the dome catching insects on the wing." },
    { id: "greater-striped-swallow", r: "Uncommon", t: "Chestnut cap and streaked underparts. Look for mud nests built under the dome structure." },
    // ══ WATERBIRDS & OTHER EXISTING ══
    { id: "woolly-necked-stork", r: "Rare", t: "A large, impressive stork — woolly white neck contrasts with glossy black body. Check near the stream and pool." },
    { id: "hadada-ibis", r: "Common", t: "Loud 'ha-da-da' call heard throughout. Often forages on the ground probing for earthworms near the path." },
    { id: "egyptian-goose", r: "Common", t: "Noisy and conspicuous near water features. Distinctive brown eye patches. Often on the ground near the stream." },
    { id: "cattle-egret", r: "Uncommon", t: "Small white egret sometimes seen foraging near the guineafowl and peafowl on the aviary floor." },
    { id: "blacksmith-lapwing", r: "Uncommon", t: "Metallic 'tink-tink' call near the water features. Bold black and white plumage is unmistakable." },
    { id: "african-sacred-ibis", r: "Uncommon", t: "White plumage with bare black head and curved bill. Often near the stream probing for invertebrates." },
    { id: "spotted-eagle-owl", r: "Rare", t: "Nocturnal but occasionally seen roosting in dense foliage during the day. Yellow eyes and ear tufts are distinctive." },
    // ══ FOREST SPECIALISTS ══
    { id: "narina-trogon", r: "Rare", t: "One of Africa's most beautiful birds. Brilliant green and red. Sits motionless in the canopy — scan carefully." },
    { id: "olive-thrush", r: "Common", t: "Familiar ground feeder with olive-brown plumage and orange belly. Flicks leaf litter aside near the walkway." },
  ]
};
PARKS.push(PARK_EDEN);
