const PARK_KRUGER = {
  id: "kruger",
  name: "Kruger National Park",
  subtitle: "South Africa's Premier Big 5 Safari",
  icon: "🦁",
  species: [
    // ══ MAMMALS — BIG 5+ ══
    { id: "african-elephant", r: "Common", t: "Huge herds along the Olifants and Letaba rivers. Over 17,000 in the park." },
    { id: "lion", r: "Common", t: "Best around Satara where open grasslands support large prey herds. Listen for roars at night." },
    { id: "leopard", r: "Uncommon", t: "Skukuza and Lower Sabie areas. Check trees along the Sabie River for resting leopards." },
    { id: "black-rhinoceros", r: "Rare", t: "Shy browser in thick bush. Best chances in the southern and southwestern sections." },
    { id: "white-rhinoceros", r: "Uncommon", t: "Grazer preferring open areas. Southern Kruger around Pretoriuskop and Lower Sabie." },
    { id: "cape-buffalo", r: "Common", t: "Large herds throughout. Check waterholes in the dry season for gatherings of hundreds." },
    // ══ MAMMALS — PREDATORS ══
    { id: "cheetah", r: "Uncommon", t: "Open grasslands around Satara are prime cheetah territory. Scan for them on termite mounds." },
    { id: "african-wild-dog", r: "Rare", t: "Packs roam widely. Pretoriuskop and southern areas. A prized sighting — report to reception." },
    { id: "spotted-hyena", r: "Common", t: "Heard calling at night throughout the park. Often seen on roads at dawn and dusk." },
    { id: "brown-hyena", r: "Rare", t: "Extremely rare in Kruger. Far more secretive and scarce than the spotted hyena." },
    { id: "honey-badger", r: "Uncommon", t: "Fearless and unpredictable. Night drives offer best sightings. Check around camp perimeters." },
    { id: "black-backed-jackal", r: "Common", t: "Common throughout, especially near rest camps at dusk. Listen for yapping calls." },
    { id: "side-striped-jackal", r: "Rare", t: "Northern Kruger around Punda Maria and Shingwedzi. White-tipped tail distinguishes from black-backed." },
    { id: "african-wildcat", r: "Rare", t: "Nocturnal. Night drives around camps. Distinguished from feral cats by reddish-brown ears." },
    { id: "african-civet", r: "Uncommon", t: "Strictly nocturnal. Night drives near rivers. Look for their distinctive spotted and banded coat." },
    { id: "small-spotted-genet", r: "Uncommon", t: "Nocturnal. Often visits rest camp dining areas. Look in rafters and trees near kitchens." },
    { id: "large-spotted-genet", r: "Uncommon", t: "Nocturnal. Similar to small-spotted but with larger rusty spots and a black-tipped tail." },
    { id: "white-tailed-mongoose", r: "Uncommon", t: "Nocturnal. White bushy tail is distinctive in headlights. Night drives near rivers." },
    { id: "banded-mongoose", r: "Common", t: "Social groups forage around rest camps. Often seen crossing roads in a busy procession." },
    { id: "dwarf-mongoose", r: "Common", t: "Groups use termite mounds as bases. Common along the H1-2 between Skukuza and Satara." },
    { id: "slender-mongoose", r: "Common", t: "Diurnal. Often darts across roads with its distinctive curved black-tipped tail held high." },
    { id: "water-mongoose", r: "Uncommon", t: "Near rivers and dams. Lake Panic hide near Skukuza is a good spot." },
    { id: "striped-polecat", r: "Rare", t: "Strictly nocturnal. Occasionally seen on night drives. Bold black-and-white warning colours." },
    { id: "caracal", r: "Rare", t: "Elusive nocturnal cat. Distinctive ear tufts. Very rarely seen — a bucket-list sighting." },
    { id: "serval", r: "Rare", t: "Tall grass areas near water. Pretoriuskop area. Large ears and spotted coat. Mostly nocturnal." },
    // ══ MAMMALS — PRIMATES ══
    { id: "vervet-monkey", r: "Common", t: "Abundant around all rest camps. Guard your food! Males have blue scrotal skin." },
    { id: "chacma-baboon", r: "Common", t: "Large troops near camps. Keep car windows closed. Never feed them." },
    { id: "southern-lesser-bushbaby", r: "Uncommon", t: "Nocturnal. Listen for wailing calls at night near camps. Huge eyes catch torch light." },
    { id: "thick-tailed-bushbaby", r: "Uncommon", t: "Nocturnal. Larger than the lesser bushbaby. Startling screaming calls at night." },
    // ══ MAMMALS — ANTELOPE ══
    { id: "impala", r: "Common", t: "Kruger's most abundant antelope. Everywhere! Their alarm snorts often signal nearby predators." },
    { id: "greater-kudu", r: "Common", t: "Magnificent spiral horns on males. Common in woodland throughout. Often browses at road edges." },
    { id: "nyala", r: "Uncommon", t: "Northern Kruger around Punda Maria and Pafuri. Males are strikingly different from females." },
    { id: "bushbuck", r: "Common", t: "Shy browser in thick riverine bush. Often seen near water at Skukuza and Lower Sabie." },
    { id: "waterbuck", r: "Common", t: "Always near water. Distinctive white ring on the rump. Common along the Sabie and Olifants rivers." },
    { id: "eland", r: "Uncommon", t: "Africa's largest antelope. More common in the north. Often in small herds in open woodland." },
    { id: "sable-antelope", r: "Rare", t: "Pretoriuskop area. Males are jet-black with white face. One of Kruger's most prized sightings." },
    { id: "roan-antelope", r: "Rare", t: "Fewer than 50 in the park. Far northern regions. Kruger's rarest large antelope." },
    { id: "tsessebe", r: "Rare", t: "Northern areas around Shingwedzi and Punda Maria. Africa's fastest antelope. Numbers declining." },
    { id: "lichtenstein-hartebeest", r: "Rare", t: "Restricted to the far north near Pafuri. One of Kruger's rarest large mammals." },
    { id: "blue-wildebeest", r: "Common", t: "Open grasslands, especially around Satara. Often mixed with zebra herds." },
    { id: "steenbok", r: "Common", t: "Small, elegant antelope. Common throughout in open woodland. Often in pairs." },
    { id: "common-duiker", r: "Common", t: "Shy and solitary. Dives into bush when disturbed. More often seen early morning." },
    { id: "klipspringer", r: "Uncommon", t: "Rocky outcrops and koppies. Stands on tiptoe on tiny hooves. Often in pairs." },
    { id: "sharpes-grysbok", r: "Rare", t: "Strictly nocturnal. Southern and central areas. Night drives offer best chances." },
    { id: "mountain-reedbuck", r: "Rare", t: "Rocky hillsides and koppies. Small groups. White bushy tail flashes when alarmed." },
    { id: "common-reedbuck", r: "Uncommon", t: "Tall grass and reed beds near water. Sharp whistling alarm call is distinctive." },
    { id: "oribi", r: "Rare", t: "One of Kruger's rarest antelope. Open grassland in scattered locations. Very few remain." },
    // ══ MAMMALS — LARGE HERBIVORES ══
    { id: "south-african-giraffe", r: "Common", t: "Tallest animal on earth. Common throughout. Often browses on roadside acacias." },
    { id: "hippopotamus", r: "Common", t: "Rivers and dams throughout. Sunset Dam at Lower Sabie is superb for close viewing." },
    { id: "burchells-zebra", r: "Common", t: "Common throughout, especially on open grasslands. Often mixed with wildebeest." },
    { id: "warthog", r: "Common", t: "'Pumba'! Runs with tail straight up. Common near camps and waterholes." },
    { id: "bushpig", r: "Rare", t: "Strictly nocturnal. Dense bush near rivers. Very rarely seen during the day." },
    // ══ MAMMALS — SMALL MAMMALS ══
    { id: "ground-pangolin", r: "Rare", t: "One of the world's rarest sightings. Strictly nocturnal. Covered in brown scales." },
    { id: "aardvark-antbear", r: "Rare", t: "Nocturnal. Look for their large burrows. Night drives offer slim chances." },
    { id: "porcupine", r: "Uncommon", t: "Nocturnal. Look for scattered quills on roads. Occasionally seen on night drives." },
    { id: "scrub-hare", r: "Common", t: "Commonly caught in headlights at dusk. Freezes before bolting into bush." },
    { id: "tree-squirrel", r: "Common", t: "Active in woodland throughout. Their shrill alarm calls warn of snakes and raptors." },
    { id: "rock-hyrax-dassie", r: "Common", t: "Bask on rocky outcrops in groups. Closest living relative of the elephant!" },
    { id: "elephant-shrew", r: "Uncommon", t: "Tiny, fast-moving insectivore with elongated nose. Scurries through leaf litter." },
    { id: "cape-hare", r: "Common", t: "Nocturnal. Frequently seen in headlights. Long ears with black tips." },
    { id: "greater-cane-rat", r: "Uncommon", t: "Near rivers and reed beds. Large rodent that looks like a small capybara." },
    { id: "african-savanna-hare", r: "Common", t: "Nocturnal. Reddish flanks distinguish from scrub hare. Common on night drives." },
    // ══ BIRDS — RAPTORS ══
    { id: "martial-eagle", r: "Uncommon", t: "Africa's largest eagle. Soars on thermals over open bush. Powerful enough to take small antelope." },
    { id: "bateleur", r: "Common", t: "Distinctive rocking flight with almost no tail. Red face and legs. Soars for hours daily." },
    { id: "african-fish-eagle", r: "Common", t: "Iconic call of Africa. Common along all major rivers and dams. Lower Sabie is excellent." },
    { id: "tawny-eagle", r: "Common", t: "Often perched on dead trees. Variable brown plumage. Scavenges at carcasses with vultures." },
    { id: "wahlbergs-eagle", r: "Common", t: "Summer migrant. Common in woodland. Small crest and longer tail than most eagles." },
    { id: "brown-snake-eagle", r: "Uncommon", t: "Large owl-like head. Perches upright in tall trees scanning for snakes. Yellow eyes." },
    { id: "african-hawk-eagle", r: "Uncommon", t: "Dramatic hunting dashes through woodland. Dark above, white below with heavy streaking." },
    { id: "gabar-goshawk", r: "Uncommon", t: "Small grey raptor with red legs. 10% are melanistic (all-black). Woodland habitat." },
    // ══ BIRDS — VULTURES ══
    { id: "white-backed-vulture", r: "Common", t: "First to arrive at carcasses. Scan the sky for circling groups as a sign of a kill nearby." },
    { id: "lappet-faced-vulture", r: "Uncommon", t: "Largest African vulture. Pink face and massive bill. Dominates at carcasses." },
    { id: "hooded-vulture", r: "Uncommon", t: "Smallest vulture. Thin bill picks scraps others leave. Often near rest camps." },
    { id: "white-headed-vulture", r: "Rare", t: "Colourful bill and white head are distinctive. Often first to spot a carcass from the air." },
    // ══ BIRDS — OWLS ══
    { id: "spotted-eagle-owl", r: "Uncommon", t: "Most common owl. Often on fence posts at dusk. Yellow eyes and ear tufts." },
    { id: "verreauxs-eagle-owl", r: "Uncommon", t: "Africa's largest owl. Pink eyelids are diagnostic. Deep booming call at night." },
    { id: "pearl-spotted-owlet", r: "Common", t: "Partly diurnal. False 'eyes' on back of head. Ascending whistle triggers small bird mobbing." },
    { id: "african-scops-owl", r: "Uncommon", t: "Tiny owl with purring 'prrp' call every 5-8 seconds on warm evenings. Master of camouflage." },
    { id: "african-barred-owlet", r: "Uncommon", t: "Dense riverine woodland. Purring, trilling call. Active at dusk. Bright yellow eyes." },
    // ══ BIRDS — GROUND BIRDS ══
    { id: "common-ostrich", r: "Common", t: "Open grasslands. Males are black with white plumes. World's largest bird at 2.7 m." },
    { id: "kori-bustard", r: "Uncommon", t: "World's heaviest flying bird. Open grasslands around Satara. Males inflate throat in display." },
    { id: "southern-ground-hornbill", r: "Uncommon", t: "Groups walk through grassland. Red facial skin. Deep booming calls carry 5 km. Vulnerable." },
    { id: "secretary-bird", r: "Uncommon", t: "Strides through grassland stomping snakes. Long crane-like legs. Declining across Africa." },
    { id: "helmeted-guineafowl", r: "Common", t: "Noisy flocks everywhere. Polka-dotted plumage. Roost in trees at night." },
    { id: "crested-francolin", r: "Common", t: "'Beer-and-cognac' dawn call is a Kruger classic. Often runs across roads ahead of vehicles." },
    { id: "swainsons-spurfowl", r: "Common", t: "Raucous crowing at dawn and dusk. Red face and legs. Common around all rest camps." },
    // ══ BIRDS — HORNBILLS ══
    { id: "southern-yellow-billed-hornbill", r: "Common", t: "The 'flying banana'. Zazu from The Lion King. Hops on ground near picnic sites." },
    { id: "southern-red-billed-hornbill", r: "Common", t: "Follows dwarf mongoose groups to catch flushed insects. Common in woodland." },
    { id: "trumpeter-hornbill", r: "Uncommon", t: "Large forest hornbill. Wailing trumpet-like call. Southern Kruger riverine forests." },
    { id: "african-grey-hornbill", r: "Common", t: "Most widespread hornbill. Plaintive 'pheeoo-pheeoo' whistle. Woodland throughout." },
    // ══ BIRDS — KINGFISHERS, BEE-EATERS, ROLLERS ══
    { id: "lilac-breasted-roller", r: "Common", t: "Africa's most beautiful bird. Perches prominently on poles and dead trees. Throughout the park." },
    { id: "european-roller", r: "Uncommon", t: "Summer migrant. Turquoise-blue body. Often perched on wires alongside roads Nov-Mar." },
    { id: "woodland-kingfisher", r: "Common", t: "Summer visitor. Loud trilling call announces arrival of the rains. Blue with red bill." },
    { id: "malachite-kingfisher", r: "Uncommon", t: "Tiny gem of blue and orange on reeds at dams and rivers. Lake Panic hide is excellent." },
    { id: "pied-kingfisher", r: "Common", t: "Hovers over water before plunging in. Black and white. Common at all rivers and dams." },
    { id: "giant-kingfisher", r: "Uncommon", t: "Africa's largest kingfisher. Perches over rivers and dams. Spotted plumage." },
    { id: "brown-hooded-kingfisher", r: "Common", t: "Woodland kingfisher that hunts insects, not fish. Red bill. Descending whistle call." },
    { id: "white-fronted-bee-eater", r: "Common", t: "Nesting colonies in riverbanks along the Olifants and Letaba rivers. Red throat." },
    { id: "little-bee-eater", r: "Common", t: "Smallest bee-eater. Perches low on twigs near water. Graceful insect-hawking sallies." },
    { id: "southern-carmine-bee-eater", r: "Uncommon", t: "Spectacular crimson-pink. Breeds on Olifants River cliffs. Sometimes rides on large animals." },
    // ══ BIRDS — WATERBIRDS ══
    { id: "saddle-billed-stork", r: "Rare", t: "Africa's tallest stork. Spectacular colourful bill. Near rivers and dams. A prized sighting." },
    { id: "yellow-billed-stork", r: "Uncommon", t: "White plumage turns pink in breeding season. Feeds by touch in shallow water." },
    { id: "marabou-stork", r: "Common", t: "Enormous scavenger often at carcasses with vultures. Bare pink head and throat sac." },
    { id: "goliath-heron", r: "Uncommon", t: "World's largest heron. Patient solitary hunter at rivers and dams. Impressive 2.3 m wingspan." },
    { id: "grey-heron", r: "Common", t: "Common at all waterholes and rivers. Patient, motionless hunter." },
    { id: "hamerkop", r: "Common", t: "Hammer-shaped head. Builds enormous 2-metre nests. Common near water throughout." },
    { id: "african-spoonbill", r: "Uncommon", t: "White wading bird with distinctive spoon-shaped bill. Sweeps through shallow water." },
    { id: "hadada-ibis", r: "Common", t: "Loud 'ha-da-da' call at dawn and dusk. Probes soft ground for earthworms." },
    { id: "egyptian-goose", r: "Common", t: "Very common at all water features. Noisy and territorial. Brown eye patches." },
    { id: "african-jacana", r: "Common", t: "Walks on lily pads with enormous feet. Sunset Dam at Lower Sabie is excellent." },
    { id: "blacksmith-lapwing", r: "Common", t: "Metallic 'tink-tink' call near water. Bold black and white. Very vocal when nesting." },
    { id: "woolly-necked-stork", r: "Uncommon", t: "Woolly white neck contrasts with glossy black body. Near rivers in woodland." },
    { id: "african-openbill", r: "Uncommon", t: "Unique bill with a gap for extracting snails. Often in flocks near shallow wetlands." },
    // ══ BIRDS — PASSERINES ══
    { id: "fork-tailed-drongo", r: "Common", t: "Glossy black expert mimic. Follows larger animals and steals food using false alarm calls." },
    { id: "burchells-coucal", r: "Common", t: "Bubbling 'water bottle' call is classic Kruger. Dense bush near water. The 'rainbird'." },
    { id: "african-hoopoe", r: "Common", t: "Cinnamon with black-and-white wings and erectile crest. Probes the ground for grubs." },
    { id: "green-wood-hoopoe", r: "Common", t: "Cackling family groups with long curved red bills. Noisy and entertaining." },
    { id: "magpie-shrike", r: "Uncommon", t: "Black and white with very long tail. Small groups perch prominently in open savanna." },
    { id: "dark-capped-bulbul", r: "Common", t: "Cheerful 'wake up, Gregory' call greets every Kruger morning. Yellow vent." },
    { id: "cape-glossy-starling", r: "Common", t: "Iridescent blue-green with orange eyes. Bold around picnic areas and camps." },
    { id: "burchells-starling", r: "Common", t: "Large glossy blue-purple starling. Dark eye distinguishes from cape glossy. Mopane woodland." },
    { id: "red-billed-oxpecker", r: "Common", t: "Clings to buffalo, giraffe, and rhino picking ticks. Red bill and yellow eye-ring." },
    { id: "yellow-billed-oxpecker", r: "Uncommon", t: "Yellow bill with red tip. Prefers buffalo and hippo. Red eye-wattle is diagnostic." },
    // ══ REPTILES ══
    { id: "nile-crocodile", r: "Common", t: "All major rivers. Sunset Dam at Lower Sabie for close viewing. Africa's largest reptile." },
    { id: "white-throated-monitor", r: "Uncommon", t: "Large lizard up to 2 metres. Basking on rocks near rivers. Forked tongue." },
    { id: "nile-monitor", r: "Uncommon", t: "Semi-aquatic. Up to 2.4 metres. Often seen near rivers and dams swimming or basking." },
    { id: "leopard-tortoise", r: "Common", t: "Often crossing roads, especially after rain. Spotted shell. One of the 'Little 5'." },
    { id: "african-rock-python", r: "Rare", t: "Africa's largest snake. Near water. Non-venomous constrictor. A dramatic sighting." },
    { id: "black-mamba", r: "Rare", t: "Africa's most feared snake. Fast and shy. Black mouth displayed when threatened." },
    { id: "mozambique-spitting-cobra", r: "Uncommon", t: "Can spit venom 3 metres targeting eyes. Near camps and buildings at night." },
    { id: "puff-adder", r: "Uncommon", t: "Relies on camouflage. Watch your step near paths. Most snakebite fatalities in Africa." },
    { id: "boomslang", r: "Rare", t: "Venomous tree snake. Males bright green, females brown. Large eyes. Very shy." },
    { id: "flap-necked-chameleon", r: "Uncommon", t: "Colour-changing. Slow, deliberate movement. Independent eyes give 360-degree vision." },
    { id: "southern-rock-agama", r: "Common", t: "Males with bright blue heads on rocks around camps. Push-up dominance displays." },
    { id: "rainbow-skink", r: "Common", t: "Iridescent scales shimmer in sunlight. Lightning-fast. Common on camp walls." },
    { id: "tropical-house-gecko", r: "Common", t: "Translucent geckos on rest camp walls and ceilings at night. Chirping calls. Eat insects." },
  ]
};
PARKS.push(PARK_KRUGER);
